//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by JamCad.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ProjectTYPE                 130
#define ID_WINDOW_MANAGER               131
#define IDR_JamCadSchType               131
#define IDR_JamCadLibType               132
#define IDR_FrontCad_TYPE               133
#define IDR_JamCadSchLibPart_TYPE       134
#define IDS_STRING135                   135
#define IDR_JamCadPCB_TYPE              136
#define IDR_JamCadPCBLib_TYPE           137
#define IDD_DIALOG_FRONTCADUTIL         310
#define IDD_DIALOG_PROPERTYEDITOR       312
#define IDD_DIALOG_PIN_PROPERTIES       314
#define IDB_PIN_LEFT                    316
#define IDB_PIN_RIGHT                   317
#define IDB_PINUP                       318
#define IDB_PINDOWN                     319
#define IDB_LINE                        320
#define IDB_CLOCK                       322
#define IDB_LINEINV                     324
#define IDB_CLOCKINV                    325
#define IDD_DIALOG_TEXT_PROPERTIES      326
#define IDD_DIALOG_LINE_ATTRB           328
#define IDD_DIALOG_RECTPROPERTIES       330
#define IDD_DIALOG_ELLIPSE_PROPERTIES   332
#define IDD_DIALOG_POLYGONPROPERTIES    334
#define IDD_DIALOG_ROUNDEDRECT_PROPERTIES 336
#define IDD_DIALOG_BITMAP_PROPERTIES    338
#define IDD_DIALOG_ARCPROPERTIES        340
#define IDD_DIALOG_ARCCENTPROPERTIES    341
#define IDD_DIALOG_POLYFILLEDPROPERTIES 342
#define IDD_DIALOG_ARROW_ATTRIBUTES     343
#define IDD_DIALOG_SCHPART_PROP         345
#define IDD_DIALOG1                     347
#define IDD_DIALOG_SCHLIB_PROP          347
#define IDC_BUTTON_PROPEDITOR_NEWCOLUMN 1000
#define IDC_BUTTON_PROPERTYEDITOR_DISPLAY 1001
#define IDC_BUTTON_PROPERTYEDITOR_APPLY 1002
#define IDC_BUTTON_PROPERTYEDITOR_DELETEPROP 1003
#define IDC_STATIC_PROPERTYEDITOR_GRID  1004
#define IDC_STATIC_PREVIEW              1005
#define IDC_EDIT_PIN_NAME               1006
#define IDC_EDIT_PIN_NUMBER             1007
#define IDC_COMBO_ELECTRICAL_TYPE       1008
#define IDC_COMBO_ORIENTATION           1009
#define IDC_COMBO_GRAPHIC_STYLE         1010
#define IDC_CHECK_ENABLE_AUTOINC        1011
#define IDC_EDIT_AUTOINC_LABEL          1012
#define IDC_EDIT_AUTOINC_PIN            1013
#define IDC_EDIT_TEXT_STRING            1014
#define IDC_CHECK_TRANSPARENT           1015
#define IDC_STATIC_TEXT_COLOR           1016
#define IDC_STATIC_BACKGROUND_COLOR     1017
#define IDC_EDIT_TEXT_HEIGHT            1018
#define IDC_EDIT_TEXT_WIDTH             1019
#define IDC_BUTTON_FONT                 1020
#define IDC_COMBO_FONTWEIGHT            1021
#define IDC_EDIT_ANGLE                  1022
#define IDC_EDIT_LINE_WIDTH             1023
#define IDC_STATIC_LINE_COLOR           1024
#define IDC_STATIC_FILL_COLOR           1026
#define IDC_STATIC_LINECOLOR            1028
#define IDC_STATIC_FILLCOLOR            1029
#define IDC_STATI_LINE_COLOR            1030
#define IDC_EDIT_LINEWIDTH              1031
#define IDC_STATI_FILL_COLOR            1032
#define IDC_EDIT_CORNERRADIUS           1033
#define IDC_EDIT_CORNERRADIUS_Y         1034
#define IDC_CHECK_MAINTAIN_ASPECT_RATIO 1035
#define IDC_EDIT_FILENAME               1036
#define IDC_BUTTON_CHOOSE_FILE          1037
#define IDC_EDIT_START_X                1039
#define IDC_EDIT_START_Y                1040
#define IDC_EDIT_END_X                  1041
#define IDC_EDIT_END_Y                  1042
#define IDC_EDIT_START_ANGLE            1043
#define IDC_EDIT_END_ANGLE              1044
#define IDC_EDIT_L1                     1045
#define IDC_EDIT_L2                     1046
#define IDC_STATIC_COLOR                1047
#define IDC_EDIT_WIDTH                  1048
#define IDC_EDIT1                       1049
#define IDC_EDIT_PINLEN                 1049
#define IDC_EDIT_PARTPROP_PARTNAME      1049
#define IDC_EDIT_PARTPROP_REFENCEDES    1050
#define IDC_EDIT_PARTPROP_UNITS         1051
#define IDC_CHECK_PARTPROP_SHOWPINNAMES 1052
#define IDC_CHECK_PARTPROP_SHOWPINNUMBERS 1053
#define IDC_CHECK_PARTPROP_NAMEINSIDE   1054
#define IDC_EDIT_NAME                   1055
#define ID_BUTTON_DEBUG                 32771
#define ID_FILE_NEW32772                32772
#define IDM_FILE_NEW_PROJECT            32773
#define IDM_FILE_NEW_SCHEMATIC          32774
#define ID_NEW_LIBRARY                  32775
#define IDM_FILE_NEW_LIB                32776
#define IDM_FILE_NEW_FRONTPANEL         32777
#define ID_FILE_NEW32778                32778
#define ID_NEW_LIBRARY32779             32779
#define IDM_FILE_NEW_LIBRARY            32780
#define IDM_SCH_PLACE_PART              32781
#define IDM_SCH_PLACE_WIRE              32782
#define ID_PLACE_BU                     32783
#define IDM_SCH__PLACE_BUSS             32784
#define IDM_SCH_PLACE_JUNCTION          32785
#define IDM_SCH_PLACE_BUSENTRY          32786
#define IDM_SCH_PLACE_NETLABEL          32787
#define IDM_SCH_PLACE_POWER             32788
#define IDM_SCH_PLACE_SCHEMATIC         32789
#define IDM_SCH_PLACE_PORT              32790
#define IDM_SCH_PLACE_SHEETPIN          32791
#define IDM_SCH_PLACE_TEXT              32792
#define IDM_SCH_PLACE_LINE              32793
#define IDM_SCH_PLACE_RECT              32794
#define IDM_SCH_PLACE_ELLISPE           32795
#define ID_PLACE_POLYGON                32796
#define IDM_SCH_PLACE_POLYGON           32797
#define ID_PLACE_FILLEDPOLYGON          32798
#define IDM_SCH_PLACE_FILLEDPOLY        32799
#define IDM_SCH_PLACE_BITMAP            32800
#define ID_BUTTON_ZOOMIN                32801
#define ID_BUTTON_ZOOMOUT               32802
#define IDM_PLACE_LINE                  32805
#define IDM_PLACE_RECT                  32806
#define ID_PLACE_ROUNDEDRECT            32807
#define IDM_PLACE_ROUNDEDRECT           32808
#define IDM_PLACE_ELLISPE               32809
#define IDM_PLACE_ARC                   32810
#define IDM_PLACE_ARCCENTER             32811
#define IDM_PLACE_POLYGON               32812
#define IDM_PLACE_POLYGONFILLED         32813
#define IDM_PLACE_LIBPART               32814
#define IDM_PLACE_BITMAP                32815
#define IDM_PLACE_HOLEROUND             32816
#define IDM_PLACE_HOLE1FLAT             32817
#define ID_PLACE_ROUNDHOLE2FLAT         32818
#define IDM_PLACE_ROUNDHOLE2FLAT        32819
#define ID_PLACE_RECTANGULARHOLE        32820
#define IDM_PLACE_RECTANGULARHOLE       32821
#define ID_PLACE_ORIGIN                 32822
#define IDM_PLACE_ORIGIN                32823
#define ID_PLACE_DIMENSION              32824
#define IDM_PLACE_DIMENSION             32825
#define IDM_PLACE_PIN                   32826
#define IDM_PLACE_REFERENCE_POINT       32827
#define IDM_PLACE_RECTANGLE             32828
#define IDM                             32829
#define IDM_PLACE_TEXT                  32830
#define IDM_PLACE_ELLIPSE               32831
#define IDM_SCH_                        32832
#define ID_PLACE_ARC                    32833
#define IDM_PLACE_ARROW                 32834

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        349
#define _APS_NEXT_COMMAND_VALUE         32835
#define _APS_NEXT_CONTROL_VALUE         1056
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
